### ISSUE TITLE
'django.contrib.sites' isn't in an application in INSTALLED_APPS.(@Django1.9.5)

### ISSUE THREAD

**Issue by xuhui546** [bread-and-pepper/django-userena#525] opened 2016-04-21 06:29 UTC
When I migrate my project from Django 1.8 to Django 1.9, I met this error.
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f741d3bbf28>
Traceback (most recent call last):
  File "/home/django19/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/django19/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/django19/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/django19/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/django19/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/django19/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/django19/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/django19/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/django19/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/django19/lib/python3.4/site-packages/userena/models.py", line 5, in <module>
    from django.contrib.sites.models import Site
  File "/home/django19/lib/python3.4/site-packages/django/contrib/sites/models.py", line 83, in <module>
    class Site(models.Model):
  File "/home/django19/lib/python3.4/site-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

So, I test the problem at 1.8 and 1.9.5.
1>Django1.8
Django (1.8)
django-guardian (1.4.1)
django-userena (2.0.1)
Everything is alright.
2>Django1.9
Django (1.9.5)
django-guardian (1.4.1)
django-userena (2.0.1)
I met the problem above.

where is my problem?
thanks.

**Comment by swistakm** [comment] 2016-04-21 09:39
@xuhui546, sorry but I had to reformat your message because it was unreadable.

In a framework like Django it's impossible to tell anything without knowing your configuration file (`settings` module). Without that I can only guess.

And my guess is: you are missing `django.contrib.sites` in your `INSTALLED_APPS` settings. Actually, I'm pretty sure that this is the problem because I was able to reproduce your issue on `Django>=1.9'` by removing this option from `INSTALLED_APPS` setting in `userena/demo` application. But I will still insist on calling it guess, because you did not provide enough information.

Requirement to add `django.contrib.sites` to list of you installed apps is already mentioned in [official documentation of userena](http://django-userena.readthedocs.org/en/latest/installation.html#required-settings).

Note that the traceback of error you posted clearly suggests that there is issue with your configuration. So in future please post also important parts of your settings file that are mentioned in traceback so it can help in finding the issue.

I'm closing this. If I did not help then please reopen, but also provide more information.

**Closed by swistakm** 2016-04-21 09:39 UTC

**Comment by xuhui546** [comment] 2016-04-22 01:35
**First of all, I am sorry for my poor English and thank you very much for your detailed reply about my trivial problem.** I'm sorry I did not look carefully document, I use the experience at django 1.8 to operate django 1.9, then I met this problem. According to your guidance I solved my problem, thanks again. :-)

**Comment by swistakm** [comment] 2016-04-22 19:03
No problem. I'm glad I could help.
