### ISSUE TITLE
Reverse for 'password_reset_done' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

### ISSUE THREAD

**Issue by deronsizemore** [bread-and-pepper/django-userena#484] opened 2015-06-04 19:08 UTC
I noticed today that I'm getting this when someone goes to: domain.com/password/reset. I really have no idea what to alter to resolve this issue. As far as I know it used to work and to my knowledge I haven't changed anything so not sure what happened.

Any ideas?

Userena 1.4
Django 1.6.8

**Comment by swistakm** [comment] 2015-06-05 11:08
You obviously have no "password_reset_done" view registered. Do you have all userena urls included? Did you change/overwrite/customized them in any way?

You should know that since very first release of django-userena each new major release of django caused many issues on userena ulrs because it relies so much on `django.contrib.auth`. You can notice that by looking at [userena.compat](https://github.com/bread-and-pepper/django-userena/blob/c3388ebffbe2bc2b859136cefce03dc2cdca526a/userena/compat.py) and [userena.urls](https://github.com/bread-and-pepper/django-userena/blob/8146b2cf2cd88d42291fb95eca2ed3122764fb15/userena/urls.py) modules. There was an issue earlier similar to what you are experiencing right now and I believe it was fixed by #381.

I believe also that such case is covered in tests so maybe the first place to look should be your ulrconf. Could you paste here an excerpt from it so I could see if it could cause such issue? I'm only interested in the parts that deal with userena and auth.

**Comment by deronsizemore** [comment] 2015-06-05 12:49
>Do you have all userena urls included? Did you change/overwrite/customized them in any way?

I'm assuming all the urls are there (at least as far as I can tell). No, nothing was changed or customized with the Userena urls.py or anything to my knowledge unless I unknowingly screwed something up but I don't believe I've ever even had that file open prior to yesterday when I saw the issue.

>here was an issue earlier similar to what you are experiencing right now and I believe it was fixed by #381.

Yes, that does sound a lot like my issue. To be quite honest, as someone who's not a django expert, I'm not exactly sure how I should proceed with implementing that fix? Would I do a pip install upgrade command and somehow tell it I want to use that version/fork? Sorry, I just don't have a lot of experience with git yet. It's next on my list of things to try to learn.

>I believe also that such case is covered in tests so maybe the first place to look should be your ulrconf. Could you paste here an excerpt from it so I could see if it could cause such issue? I'm only interested in the parts that deal with userena and auth.

It looks to me like this is the only bit of code in my urls.py for Userena that deal with user auth. Please let me know if this isn't what you need:

   # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt',
        'extra_context': {'without_usernames': userena_settings.USERENA_WITHOUT_USERNAMES}
        },
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

**Comment by deronsizemore** [comment] 2015-06-05 13:01
I noticed the changes made here to urls.py: https://github.com/bread-and-pepper/django-userena/pull/381/files

I tried adding:

    #Django.contrib.auth.views expects this url to be named password_reset_done
    # made a second copy to comply
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        {'template_name': 'userena/password_reset_done.html'},
        name='password_reset_done'),

Instead of a 500, I get a 404 with that change.

**Comment by swistakm** [comment] 2015-06-05 14:29
Ok, thanks for this excerpt of your urlconf. Now I see the issue. I think that what you have pasted here is a copy of some of `userena/urls.py` code from version <=1.2.4. This is not a reliable way to install userena urls. I would advise you to do this in a way that is  [recommended by userena's documentation](http://django-userena.readthedocs.org/en/latest/installation.html?highlight=include#the-uri-s):
 ```
(r'^accounts/', include('userena.urls')),
 ```

Where `r'accounts/'` is only a proposed name for url node. Of course you can include somewhere else, e.g in root.

Note that this is the usual approach for most of django packages that expose any urls.

**Comment by deronsizemore** [comment] 2015-06-05 15:24
I apologize, I guess I misunderstood what you were asking me for earlier. What I pasted was from the userena urls.py file. For my project urls.py file, I am doing what you mentioned:

    url(r'^activate/(?P<activation_key>\w+)/$', 'accounts.views.activate', name='userena_activate'),
    url(r'^signup/$', 'userena.views.signup', {'signup_form': SignupFormExtra}),
    url(r'^(?P<username>[\.\w-]+)/password/$', accounts.views.password_change, name='userena_password_change'), # this was added only for @parsleyfy on the form.py
    url(r'^(?P<username>[\.\w-]+)/edit/', 'userena.views.profile_edit', {'edit_profile_form': EditProfileFormExtra}, name='userena_profile_edit'),
    url(r'^', include('userena.urls')),
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w-]+)/', include('accounts.urls')),

I added a few other lines in there because I edited a few things with Userena, but nothing dealing with the forgot password form (but that doesn't mean I didn't inadvertently break something).

I'm assuming the relevant line above is: url(r'^', include('userena.urls')),

**Comment by swistakm** [comment] 2015-06-05 16:21
So check if you have really using userena==1.4.0 because what you have pasted looks like userena urls from version <= 1.2.4 and there is no proper 'post_reset_redirect' set in 'userena_password_reset_view'. For django <= 1.6 it was 'password_reset_done' which is exposed by django.contrib.auth urls but for later versions it should be 'userena_password_reset_done'.

-----Wiadomość oryginalna-----
Od: Deron Sizemore
Wysłano: 2015-06-05 17:24
Do: bread-and-pepper/django-userena
DW: Michał Jaworski
Temat: Re: [django-userena] Reverse for 'password_reset_done' with arguments'()' and keyword arguments '{}' not found. 0 pattern(s) tried: [] (#484)

I apologize, I guess I misunderstood what you were asking me for earlier. What I pasted was from the userena urls.py file. For my project urls.py file, I am doing what you mentioned:
url(r'^activate/(?P<activation_key>\w+)/$', 'accounts.views.activate', name='userena_activate'),
url(r'^signup/$', 'userena.views.signup', {'signup_form': SignupFormExtra}),
url(r'^(?P<username>[\.\w-]+)/password/$', accounts.views.password_change, name='userena_password_change'), # this was added only for @parsleyfy on the form.py
url(r'^(?P<username>[\.\w-]+)/edit/', 'userena.views.profile_edit', {'edit_profile_form': EditProfileFormExtra}, name='userena_profile_edit'),
url(r'^', include('userena.urls')),
url(r'^(?P<username>(?!signout|signup|signin)[\.\w-]+)/', include('accounts.urls')),

 I added a few other lines in there because I edited a few things with Userena, but nothing dealing with the forgot password form (but that doesn't mean I didn't inadvertently break something).

I'm assuming the relevant line above is: url(r'^', include('userena.urls')),

**Comment by deronsizemore** [comment] 2015-06-05 16:53
You're correct. I'm on Userena 1.2.3. Sorry about that. For some reason Userena wasn't showing in pip freeze in my local development environment but it seems to be on my production environment which they both would be the same version.

So, you're correct. That said, where do I go from here? Should I simply upgrade Userena to a newer version? I guess I've always been hesitant to do that for fear that it would end up breaking something else upon upgrade.

**Comment by swistakm** [comment] 2015-06-06 12:54
I think you should upgrade to `1.4.1`.
Think about this in that way:

0. what you have reported here is an obvious bug of `userena==1.2.3`.
0. fixing that bug would require changes that creates new release of userena
0. using that fixes would require you to update userena in you project.

So since points 1. & 2. already happened in past there is no other solution to your problem than 3.

Of course I could give you a guidance how to hack your url's in order to avoid upgrading but I won't do that for following reasons:

0. this is complicated.
0. this will make your urlconf a mess and increase your technology debt
0. version of userena you are currently using is **not campatibile** with your version of django so you can experience more issues in near future that can also are fixed with newer versions
0. this only increases your technology debt since such hacks would make you harder to migrate into newer versions of django

If you are afraid of upgrading to new version here is a [list of all backwards incompatibile changes](https://github.com/bread-and-pepper/django-userena/blob/master/UPDATES). Best way to ensure that nothing is broken is to provide as much tests coverage as it is reasonable.

I think that we can close this issue. We found root cause and there is a solution provided.

**Comment by deronsizemore** [comment] 2015-06-06 15:12
I tried running: pip install --upgrade django-userena==1.4.1

and as a result it attempts to download and upgrade all the things, it seems. How can I simply upgrade django-userena without upgrading django itself? I've had this happen before with userena and other packages and it's frustrating because I don't want to be on django 1.8 but it seems to force it upon you when doing an upgrade. what am I doing wrong here?

**Comment by deronsizemore** [comment] 2015-06-06 15:22
Ok, well I found how to install without dependencies using: pip install -U --no-deps django-userena==1.4.1 which seems to have only upgraded userena and nothing else and userena is now showing in pip freeze as 1.4.1.

however, when loading /password/reset/, I'm getting a 404 now rather than 500.

**Comment by swistakm** [comment] 2015-06-08 12:07
I have tried to reproduce this on your version of django and userena urls included in root:

    (r'^', include('userena.urls')),

but everything works fine. 404 means that there is no such url registered in urlconf so this is the place where you should look. When getting 404 with `DEBUG=True`you should get list of urls templates that django tried to find like:

```
Using the URLconf defined in userena.runtests.urls, Django tried these URL patterns, in this order:
^admin/doc/
^admin/
^ ^signup/$ [name='userena_signup']
^ ^signin/$ [name='userena_signin']
^ ^signout/$ [name='userena_signout']
^ ^password/reset/$ [name='userena_password_reset']
^ ^password/reset/done/$ [name='userena_password_reset_done']
^ ^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$ [name='userena_password_reset_confirm']
^ ^password/reset/confirm/complete/$ [name='userena_password_reset_complete']
^ ^(?P<username>[\@\.\w-]+)/signup/complete/$ [name='userena_signup_complete']
^ ^activate/(?P<activation_key>\w+)/$ [name='userena_activate']
^ ^activate/retry/(?P<activation_key>\w+)/$ [name='userena_activate_retry']
^ ^(?P<username>[\@\.\w-]+)/email/$ [name='userena_email_change']
^ ^(?P<username>[\@\.\w-]+)/email/complete/$ [name='userena_email_change_complete']
^ ^(?P<username>[\@\.\w-]+)/confirm-email/complete/$ [name='userena_email_confirm_complete']
^ ^confirm-email/(?P<confirmation_key>\w+)/$ [name='userena_email_confirm']
^ ^(?P<username>[\@\.\w-]+)/disabled/$ [name='userena_disabled']
^ ^(?P<username>[\@\.\w-]+)/password/$ [name='userena_password_change']
^ ^(?P<username>[\@\.\w-]+)/password/complete/$ [name='userena_password_change_complete']
^ ^(?P<username>[\@\.\w-]+)/edit/$ [name='userena_profile_edit']
^ ^(?P<username>(?!signout|signup|signin)[\@\.\w-]+)/$ [name='userena_profile_detail']
^ ^page/(?P<page>[0-9]+)/$ [name='userena_profile_list_paginated']
^ ^$ [name='userena_profile_list']
^messages/
^i18n/
^static\/(?P<path>.*)$
^media\/(?P<path>.*)$
```
Do you have such output?

Anyway you should check if you don't have too greedy url patterns before userena urls that can also match `/password/reset/` and raise 404 error. 

Anyway it is better to include userena urls with some prefix (e.g. accounts like in docs) because including in root will clutter your root "namespace" and can cause issues that are hard to find if you don't remember all patterns used in all apps.

**Comment by deronsizemore** [comment] 2015-06-08 14:28
Thanks, all of what you're saying makes sense. I just can't figure out why I'm seeing different things than I should be seeing. I'm not getting a list of url templates that django tried to find. All I'm getting on the default debug=True 404 error page is the message:

>No User matches the given query.

So, that seems to indicate that it's trying to find a profile of /password/ which doesn't exist and is returning a 404 because user doesn't exist. That said,  I went into my urlconf and commented out all lines looking for a username after the first forward slash and it gives me the same thing.

I also went in and changed my userena line in urlconf to:

>url(r'^profile/', include('userena.urls')),

That also has no affect on the issue.

I've tried moving the userena urlconf line up to be first in the order so it gets hit first and that has no affect on the issue.

I mean, at this point I guess it seems it's not a userena issue. I just can't seem to figure out why changing my urlsconf around seemingly has zero affect on the issue at all, but I'll continue playing around with it.

Thanks

**Comment by swistakm** [comment] 2015-06-08 15:11
Maybe try commenting **absolutely all** urls except userena as a starting point. Anyway moving the includes for userena up in urlconf should be enough so I have no idea why this did not help.

I don't know all of your patterns but also pay attention to those that are not ending with `$` in cases when they should. From your code samples I noticed that some of your urls tend to miss this (e.g. url for `userena.views.profile_edit`)

**Comment by deronsizemore** [comment] 2015-06-08 15:23
Thanks again. That appears to be the only line where I missed the "$" at the end, which didn't have any effect on the issue at hand.

>Maybe try commenting absolutely all urls except userena as a starting point.

Yeah, tried that too. I end up getting a lot of "not a registered namespace" errors which appear to be related to all of the url lines I commented out. So, I uncommented them one by one for each error until the namespace errors go away and then at that point I have my userena urls.py line along with four other lines and then I'm right back to the No User matches the given query error.

Anyway, I appreciate your help.

**Comment by deronsizemore** [comment] 2015-08-19 17:24
Well I finally tracked down this issue to the password_reset_message.txt template. I'm using Userena 1.4.1 and had this line in that template:

    {{ protocol }}://{{ domain }}{% url 'userena_password_reset_confirm' uidb36=uid token=token %}

The "uidb36=uid token=token" part had to be changed to just "uid token" and then it worked fine.

In looking at the template here on github, I see that it's not the same as what I had, so I honestly have no idea where that code would have come from as it's not something I would have ever messed with. But at any rate, it's fixed and hopefully someone else may find this useful.

Thanks.

**Closed** 2015-08-19 17:24 UTC
Labels: question
