### ISSUE TITLE
Group support for django-userena

### ISSUE THREAD

**Issue by bittner** [bread-and-pepper/django-userena#513] opened 2016-01-26 10:49 UTC
It would be helpful to have group support included in userena by default.

Ideally, this should create and use Django's groups functionality of [django.contrib.auth](https://docs.djangoproject.com/en/1.9/ref/contrib/auth/). An example attempt is posted [on StackOverflow](http://stackoverflow.com/questions/14508051/handle-various-groups-of-users-profiles-with-django-userena). Messaging could then happen within those user groups, not between (explicitly defined) single users as today.

Any plans on implementing this? Or reasons why this is (not going to happen or) better not done?

**Comment by swistakm** [comment] 2016-01-29 11:17
Please be more specific. What do you mean by "group support"? Userena is built on top of `django.contrib.auth` so it is compatible with groups by definition.

If by support you mean only the messaging provided by `umessages` then you should be still more specific. What do you mean by messaging within groups? Groups of contacts? Channels? Rooms? Broadcasts?

Still, I don't think that we will support group messaging in `umessages` because it was designed only to solve one simple problem and anything else. It is very unlikely we could extend it's scope without tremendous effort and complete redesign. Reason for that is simple: messaging, despite for many of us seems trivial, is in fact an extremely hard and complex topic.

If you need something more complex then you should search for a better solution designed to solve various messaging patterns in Django exclusively. If it is build with Django's built-in auth in mind then it is probably also compatible with userena. 

My personal opinion is that if such complex messaging has to be one of core features that your users will use often then you should forget about any messaging built on top of Django's ORM. Technologies built exclusively for messaging like XMPP, or e-mail are usually the best choice in such situations.

**Comment by swistakm** [comment] 2016-03-22 16:29
I close this because there was no further discussion.

**Closed by swistakm** 2016-03-22 16:29 UTC
Labels: question
